# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'stockPlotUi.ui'
##
## Created by: Qt User Interface Compiler version 6.2.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSpacerItem,
    QSpinBox, QStatusBar, QTabWidget, QTableView,
    QVBoxLayout, QWidget)

from pyqtgraph.dockarea import DockArea

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.ApplicationModal)
        MainWindow.resize(1949, 1365)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionOpenDialog = QAction(MainWindow)
        self.actionOpenDialog.setObjectName(u"actionOpenDialog")
        self.actionQuit2 = QAction(MainWindow)
        self.actionQuit2.setObjectName(u"actionQuit2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.dockWidget = DockArea(self.centralwidget)
        self.dockWidget.setObjectName(u"dockWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy1)

        self.gridLayout_2.addWidget(self.dockWidget, 0, 0, 1, 1)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(-1, 10, 10, 0)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        font = QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout.addWidget(self.label_7)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy2)
        self.groupBox.setMinimumSize(QSize(350, 80))
        self.groupBox.setMaximumSize(QSize(350, 80))
        self.groupBox.setSizeIncrement(QSize(0, 0))
        font1 = QFont()
        font1.setPointSize(14)
        self.groupBox.setFont(font1)
        self.layoutWidget = QWidget(self.groupBox)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 13, 323, 54))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")
        sizePolicy2.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy2)
        self.label_2.setMaximumSize(QSize(140, 23))
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_2.setMargin(0)
        self.label_2.setIndent(15)

        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.lineEdit = QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")
        sizePolicy2.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy2)
        self.lineEdit.setMinimumSize(QSize(180, 23))
        self.lineEdit.setMaximumSize(QSize(180, 23))
        self.lineEdit.setFont(font1)

        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)

        self.label_9 = QLabel(self.layoutWidget)
        self.label_9.setObjectName(u"label_9")
        sizePolicy2.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy2)
        self.label_9.setMaximumSize(QSize(140, 23))
        self.label_9.setFont(font1)
        self.label_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_9.setIndent(15)

        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)

        self.lineEdit_TickSyml = QLineEdit(self.layoutWidget)
        self.lineEdit_TickSyml.setObjectName(u"lineEdit_TickSyml")
        sizePolicy2.setHeightForWidth(self.lineEdit_TickSyml.sizePolicy().hasHeightForWidth())
        self.lineEdit_TickSyml.setSizePolicy(sizePolicy2)
        self.lineEdit_TickSyml.setMinimumSize(QSize(180, 23))
        self.lineEdit_TickSyml.setMaximumSize(QSize(180, 23))
        self.lineEdit_TickSyml.setFont(font1)

        self.gridLayout.addWidget(self.lineEdit_TickSyml, 1, 1, 1, 1)


        self.verticalLayout.addWidget(self.groupBox)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy3)
        self.label_20.setMinimumSize(QSize(40, 0))
        self.label_20.setMaximumSize(QSize(40, 16777215))
        self.label_20.setFont(font1)
        self.label_20.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_20.setIndent(10)

        self.horizontalLayout_5.addWidget(self.label_20)

        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        sizePolicy3.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy3)
        self.label_21.setMinimumSize(QSize(47, 0))
        self.label_21.setMaximumSize(QSize(47, 16777215))
        self.label_21.setFont(font1)
        self.label_21.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_21.setIndent(0)

        self.horizontalLayout_5.addWidget(self.label_21)

        self.SB_sma_short = QSpinBox(self.centralwidget)
        self.SB_sma_short.setObjectName(u"SB_sma_short")
        self.SB_sma_short.setMinimumSize(QSize(50, 0))
        self.SB_sma_short.setMaximumSize(QSize(50, 16777215))
        self.SB_sma_short.setFont(font1)
        self.SB_sma_short.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_sma_short.setMinimum(1)
        self.SB_sma_short.setMaximum(500)
        self.SB_sma_short.setValue(5)

        self.horizontalLayout_5.addWidget(self.SB_sma_short)

        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        sizePolicy3.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy3)
        self.label_19.setMaximumSize(QSize(40, 16777215))
        self.label_19.setFont(font1)
        self.label_19.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_19.setIndent(0)

        self.horizontalLayout_5.addWidget(self.label_19)

        self.SB_sma_med = QSpinBox(self.centralwidget)
        self.SB_sma_med.setObjectName(u"SB_sma_med")
        sizePolicy2.setHeightForWidth(self.SB_sma_med.sizePolicy().hasHeightForWidth())
        self.SB_sma_med.setSizePolicy(sizePolicy2)
        self.SB_sma_med.setMinimumSize(QSize(50, 0))
        self.SB_sma_med.setMaximumSize(QSize(50, 16777215))
        self.SB_sma_med.setFont(font1)
        self.SB_sma_med.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_sma_med.setMinimum(1)
        self.SB_sma_med.setMaximum(500)
        self.SB_sma_med.setValue(20)

        self.horizontalLayout_5.addWidget(self.SB_sma_med)

        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        sizePolicy3.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy3)
        self.label_18.setMaximumSize(QSize(40, 16777215))
        self.label_18.setFont(font1)
        self.label_18.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_18.setIndent(0)

        self.horizontalLayout_5.addWidget(self.label_18)

        self.SB_sma_long = QSpinBox(self.centralwidget)
        self.SB_sma_long.setObjectName(u"SB_sma_long")
        self.SB_sma_long.setMinimumSize(QSize(50, 0))
        self.SB_sma_long.setMaximumSize(QSize(50, 16777215))
        self.SB_sma_long.setFont(font1)
        self.SB_sma_long.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.SB_sma_long.setMinimum(1)
        self.SB_sma_long.setMaximum(500)
        self.SB_sma_long.setValue(60)

        self.horizontalLayout_5.addWidget(self.SB_sma_long)


        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy4)
        self.label.setMaximumSize(QSize(150, 16777215))
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label.setIndent(10)

        self.horizontalLayout_2.addWidget(self.label)

        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setMaximumSize(QSize(200, 16777215))
        self.comboBox.setFont(font1)

        self.horizontalLayout_2.addWidget(self.comboBox)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.tableView = QTableView(self.centralwidget)
        self.tableView.setObjectName(u"tableView")
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMaximumSize(QSize(350, 16777215))
        self.tableView.setBaseSize(QSize(0, 15))
        self.tableView.setFont(font1)
        self.tableView.setFrameShape(QFrame.StyledPanel)
        self.tableView.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.tableView.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableView.verticalHeader().setVisible(False)

        self.verticalLayout.addWidget(self.tableView)

        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_5.setMargin(7)

        self.verticalLayout.addWidget(self.label_5)

        self.tabWidget_2 = QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        sizePolicy2.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy2)
        self.tabWidget_2.setMinimumSize(QSize(350, 230))
        self.tabWidget_2.setFont(font1)
        self.tabWidget_2.setTabShape(QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(Qt.ElideMiddle)
        self.tabWidget_2.setUsesScrollButtons(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tab_SMACross = QWidget()
        self.tab_SMACross.setObjectName(u"tab_SMACross")
        self.label_11 = QLabel(self.tab_SMACross)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 11, 60, 16))
        self.label_11.setFont(font1)
        self.label_12 = QLabel(self.tab_SMACross)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(21, 98, 70, 21))
        self.label_12.setMaximumSize(QSize(70, 16777215))
        self.label_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_13 = QLabel(self.tab_SMACross)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(181, 98, 70, 21))
        self.label_13.setMaximumSize(QSize(70, 16777215))
        self.label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.spinBox_Short = QSpinBox(self.tab_SMACross)
        self.spinBox_Short.setObjectName(u"spinBox_Short")
        self.spinBox_Short.setGeometry(QRect(101, 98, 70, 24))
        self.spinBox_Short.setMaximumSize(QSize(70, 16777215))
        self.spinBox_Short.setAlignment(Qt.AlignCenter)
        self.spinBox_Short.setMinimum(5)
        self.spinBox_Long = QSpinBox(self.tab_SMACross)
        self.spinBox_Long.setObjectName(u"spinBox_Long")
        self.spinBox_Long.setGeometry(QRect(261, 98, 70, 24))
        self.spinBox_Long.setMaximumSize(QSize(70, 16777215))
        self.spinBox_Long.setAlignment(Qt.AlignCenter)
        self.spinBox_Long.setMinimum(20)
        self.lineEdit_cash = QLineEdit(self.tab_SMACross)
        self.lineEdit_cash.setObjectName(u"lineEdit_cash")
        self.lineEdit_cash.setGeometry(QRect(100, 11, 113, 21))
        self.label_14 = QLabel(self.tab_SMACross)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 43, 71, 16))
        self.label_14.setFont(font1)
        self.lineEdit_commision = QLineEdit(self.tab_SMACross)
        self.lineEdit_commision.setObjectName(u"lineEdit_commision")
        self.lineEdit_commision.setGeometry(QRect(100, 40, 113, 21))
        self.lineEdit_margin = QLineEdit(self.tab_SMACross)
        self.lineEdit_margin.setObjectName(u"lineEdit_margin")
        self.lineEdit_margin.setGeometry(QRect(101, 69, 113, 21))
        self.lineEdit_margin.setAutoFillBackground(False)
        self.lineEdit_margin.setInputMethodHints(Qt.ImhDigitsOnly)
        self.label_15 = QLabel(self.tab_SMACross)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(21, 72, 71, 16))
        self.label_15.setFont(font1)
        self.label_16 = QLabel(self.tab_SMACross)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 133, 100, 21))
        self.label_16.setMaximumSize(QSize(100, 16777215))
        self.label_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_17 = QLabel(self.tab_SMACross)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 169, 100, 21))
        self.label_17.setMaximumSize(QSize(100, 16777215))
        self.label_17.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.comboBox_ToC = QComboBox(self.tab_SMACross)
        self.comboBox_ToC.addItem("")
        self.comboBox_ToC.addItem("")
        self.comboBox_ToC.setObjectName(u"comboBox_ToC")
        self.comboBox_ToC.setGeometry(QRect(140, 133, 131, 26))
        self.comboBox_ToC.setMaximumSize(QSize(200, 16777215))
        self.comboBox_EO = QComboBox(self.tab_SMACross)
        self.comboBox_EO.addItem("")
        self.comboBox_EO.addItem("")
        self.comboBox_EO.setObjectName(u"comboBox_EO")
        self.comboBox_EO.setGeometry(QRect(140, 169, 131, 26))
        self.comboBox_EO.setMaximumSize(QSize(200, 16777215))
        self.tabWidget_2.addTab(self.tab_SMACross, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget_2.addTab(self.tab_3, "")

        self.verticalLayout.addWidget(self.tabWidget_2)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        sizePolicy3.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy3)
        self.label_4.setMinimumSize(QSize(40, 0))
        self.label_4.setMaximumSize(QSize(40, 16777215))
        self.label_4.setFont(font1)

        self.horizontalLayout.addWidget(self.label_4)

        self.lineEdit_start_region = QLineEdit(self.centralwidget)
        self.lineEdit_start_region.setObjectName(u"lineEdit_start_region")
        sizePolicy2.setHeightForWidth(self.lineEdit_start_region.sizePolicy().hasHeightForWidth())
        self.lineEdit_start_region.setSizePolicy(sizePolicy2)
        self.lineEdit_start_region.setMinimumSize(QSize(120, 21))
        self.lineEdit_start_region.setMaximumSize(QSize(120, 21))
        self.lineEdit_start_region.setFont(font1)
        self.lineEdit_start_region.setReadOnly(True)

        self.horizontalLayout.addWidget(self.lineEdit_start_region)

        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        sizePolicy3.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy3)
        self.label_6.setMinimumSize(QSize(40, 0))
        self.label_6.setMaximumSize(QSize(40, 16777215))
        self.label_6.setFont(font1)

        self.horizontalLayout.addWidget(self.label_6)

        self.lineEdit_end_region = QLineEdit(self.centralwidget)
        self.lineEdit_end_region.setObjectName(u"lineEdit_end_region")
        sizePolicy2.setHeightForWidth(self.lineEdit_end_region.sizePolicy().hasHeightForWidth())
        self.lineEdit_end_region.setSizePolicy(sizePolicy2)
        self.lineEdit_end_region.setMinimumSize(QSize(120, 21))
        self.lineEdit_end_region.setMaximumSize(QSize(120, 21))
        self.lineEdit_end_region.setReadOnly(True)

        self.horizontalLayout.addWidget(self.lineEdit_end_region)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.tableView_backtesting = QTableView(self.centralwidget)
        self.tableView_backtesting.setObjectName(u"tableView_backtesting")
        sizePolicy.setHeightForWidth(self.tableView_backtesting.sizePolicy().hasHeightForWidth())
        self.tableView_backtesting.setSizePolicy(sizePolicy)
        self.tableView_backtesting.setMinimumSize(QSize(350, 0))
        self.tableView_backtesting.setMaximumSize(QSize(350, 16777215))
        self.tableView_backtesting.setFont(font1)
        self.tableView_backtesting.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout.addWidget(self.tableView_backtesting)


        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(10, -1, 10, 10)
        self.horizontalSpacer_2 = QSpacerItem(765, 17, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.quitButton = QPushButton(self.centralwidget)
        self.quitButton.setObjectName(u"quitButton")
        sizePolicy2.setHeightForWidth(self.quitButton.sizePolicy().hasHeightForWidth())
        self.quitButton.setSizePolicy(sizePolicy2)
        self.quitButton.setFont(font1)

        self.horizontalLayout_3.addWidget(self.quitButton)


        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1949, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionOpenDialog)
        self.menuFile.addAction(self.actionQuit2)

        self.retranslateUi(MainWindow)
        self.quitButton.clicked.connect(MainWindow.close)
        self.actionQuit2.triggered.connect(MainWindow.close)

        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionOpenDialog.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionQuit2.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u9298\u67c4\u6307\u5b9a", None))
        self.groupBox.setTitle("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Search NASDAQ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"from Alphavantage", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"SMA :", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Short", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Med.", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Long", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Time Span", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Daily", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"60min", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"30min", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"15min", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"5min", None))

        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u691c\u8a3c(backtesting.py)", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Cash", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"SMA Short", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"SMA Long", None))
        self.lineEdit_cash.setText(QCoreApplication.translate("MainWindow", u"1000", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Commision", None))
        self.lineEdit_commision.setText(QCoreApplication.translate("MainWindow", u"0.00495", None))
        self.lineEdit_margin.setText(QCoreApplication.translate("MainWindow", u"1.0", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Margin", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Trade on Close", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Exclusive Orders", None))
        self.comboBox_ToC.setItemText(0, QCoreApplication.translate("MainWindow", u"True", None))
        self.comboBox_ToC.setItemText(1, QCoreApplication.translate("MainWindow", u"False", None))

        self.comboBox_EO.setItemText(0, QCoreApplication.translate("MainWindow", u"True", None))
        self.comboBox_EO.setItemText(1, QCoreApplication.translate("MainWindow", u"False", None))

        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_SMACross), QCoreApplication.translate("MainWindow", u"SmaCross", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Page", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Start :", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"End :", None))
        self.quitButton.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

